version: "2.3"

services:
  gobbli-benchmark-gpu:
    runtime: nvidia
    ipc: host
    build:
      context: ../
      dockerfile: ./benchmark/docker/Dockerfile
    image: gobbli-benchmark:latest
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      GOBBLI_USE_GPU: "1"
    shm_size: 4G
    volumes:
      # Needed to spawn containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Needed to perform bind mounts as we would on the host
      - $PWD:$PWD
    working_dir: $PWD

  gobbli-benchmark:
    build:
      context: ../
      dockerfile: ./benchmark/docker/Dockerfile
    image: gobbli-benchmark:latest
    shm_size: 4G
    volumes:
      # Needed to spawn containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Needed to perform bind mounts as we would on the host
      - $PWD:$PWD
    working_dir: $PWD
