language: minimal

env:
  jobs:
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

services:
  - docker

install:
  - cd ci
  - docker-compose build gobbli-ci

script:
  - docker-compose run --rm gobbli-ci
