version: "3.3"

services:
  gobbli-ci:
    build:
      context: ../
      args:
        PYTHON_VERSION: "${PYTHON_VERSION:?Must specify Python version.}"
    image: gobbli-ci:latest
    ipc: host
    # Travis only gives us ~7.5GB of memory, so we need to run tests in
    # low resource mode
    # The test environment won't be shared across runs, but we'd like to reuse
    # artifacts between tests where possible to reduce runtime, so add the
    # switch to persist data as well
    command: ./run_ci.sh --low-resource --persist-data
    working_dir: $PWD/..
    volumes:
      # Needed for CI to be able to spawn containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Needed for CI to perform bind mounts as we would on the host
      - $PWD/..:$PWD/..
